### ISSUE TITLE
Standardize styles and views for the whole application

### ISSUE THREAD

**Issue by xus84** [smarcilla/easy-personal-finance-app#18]
We need to standardize the navigation bar and styles used in the application. 
This will improve the overall look and feel of the application and make it easier for users to navigate.

**Comment by smarcilla** [comment]
Yes, but styles you are the master 

Respect navigation or user experience. I can test it but I need to see your changes before.

**Comment by smarcilla** [comment]
![image](https://user-images.githubusercontent.com/4559278/217538687-9292b654-c5e0-4655-bacd-e4fdb1246c06.png)

I think that we can move tittle below to navigation bar. 

@xus84 This issue is 18# but branch is feature-17-styles...

remember that pattern should be feature-{issue-number}
